<?

/*
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_%d0%b3%d0%bb%d0%b0%d0%b2%d0%bd%d0%b0%d1%8f',
		'title' => 'Главная',
		'fields' => array (
			array (
				'key' => 'field_56370c849f6d0',
				'label' => 'Преимущество №1 Заголовок',
				'name' => 'feature-1-header',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5637083730bb0',
				'label' => 'Преимущество №1 Текст',
				'name' => 'feature-1',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5637089b30bb1',
				'label' => 'Преимущество №1 SVG Иконка',
				'name' => 'feature-1-icon',
				'type' => 'text',
				'instructions' => 'В папке шаблона ~/dist/images/svg',
				'default_value' => 'line/heart.svg',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56370cb041a1c',
				'label' => 'Преимущество №2 Заголовок',
				'name' => 'feature-2-header',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5637095b5d8f8',
				'label' => 'Преимущество №2 Текст',
				'name' => 'feature-2',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_563709a0ccf78',
				'label' => 'Преимущество №2 SVG Иконка',
				'name' => 'feature-2-icon',
				'type' => 'text',
				'instructions' => 'В папке шаблона ~/dist/images/svg',
				'default_value' => 'line/wine.svg',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56370cb141a1d',
				'label' => 'Преимущество №3 Заголовок',
				'name' => 'feature-3-header',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56370983ee7d7',
				'label' => 'Преимущество №3 Текст',
				'name' => 'feature-3',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_563709a0ccf77',
				'label' => 'Преимущество №3 SVG Иконка',
				'name' => 'feature-3-icon',
				'type' => 'text',
				'instructions' => 'В папке шаблона ~/dist/images/svg',
				'default_value' => 'line/gift.svg',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5637099dccf76',
				'label' => 'Баннер',
				'name' => '',
				'type' => 'message',
				'message' => 'Можно использовать как описание для акции или нового блюда',
			),
			array (
				'key' => 'field_56370dd254ce2',
				'label' => 'Заголовок баннера',
				'name' => 'banner-header',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56370e1554ce3',
				'label' => 'Текст баннера',
				'name' => 'banner-text',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56370e7bec6b3',
				'label' => 'Иконка баннера',
				'name' => 'banner-icon',
				'type' => 'textarea',
				'instructions' => 'HTML-код SVG или Webfont иконки',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 2,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56370eb2ec6b4',
				'label' => 'Фоновое изображение',
				'name' => 'banner-image',
				'type' => 'text',
				'default_value' => 'chetverg/food/1',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56370eefec6b5',
				'label' => 'Параметры анимации фона',
				'name' => 'banner-image-parallax',
				'type' => 'text',
				'instructions' => 'Не изменять',
				'default_value' => '"y" : -150, "smoothness": 50, "scale": 1.15',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-main.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '96',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_%d0%bc%d0%b5%d0%bd%d1%8e',
		'title' => 'Меню',
		'fields' => array (
			array (
				'key' => 'field_5632b4e383c0c',
				'label' => 'Описание',
				'name' => 'menu-description',
				'type' => 'textarea',
				'instructions' => 'Описание (состав)',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 5,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5632b443e2ee9',
				'label' => 'Цена',
				'name' => 'menu-price',
				'type' => 'text',
				'instructions' => 'Cтоимость блюда',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 5,
			),
			array (
				'key' => 'field_5632b461e2eea',
				'label' => 'Вес',
				'name' => 'menu-weight',
				'type' => 'text',
				'instructions' => 'Вес',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5632f47dee374',
				'label' => 'Изображение',
				'name' => 'menu-image',
				'type' => 'image',
				'instructions' => 'Фото блюда',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5632f4b1ee375',
				'label' => 'М-Вкусно',
				'name' => 'menu-mvkusno',
				'type' => 'text',
				'instructions' => 'Ссылка на страницу блюда в М-Вкусно',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'menu_db',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_%d1%80%d0%b5%d1%81%d1%82%d0%be%d1%80%d0%b0%d0%bd',
		'title' => 'Ресторан',
		'fields' => array (
			array (
				'key' => 'field_5632d42337f09',
				'label' => 'О ресторане',
				'name' => 'the-about',
				'type' => 'textarea',
				'instructions' => 'Описание ресторана, вкратце о ресторане',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5632c32300481',
				'label' => 'Телефон',
				'name' => 'phone-number',
				'type' => 'text',
				'instructions' => 'Телефонный номер',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_56331f2e90bca',
				'label' => 'Адрес',
				'name' => 'where',
				'type' => 'text',
				'instructions' => 'Адрес ресторана',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5632c2b9a3c90',
				'label' => 'Время работы',
				'name' => 'work-time',
				'type' => 'text',
				'instructions' => 'Время работы ресторана',
				'required' => 1,
				'default_value' => 'с 11:00 до 2:00',
				'placeholder' => 'с 11:00 до 2:00',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 25,
			),
			array (
				'key' => 'field_5632ca9aedac5',
				'label' => 'График работы',
				'name' => 'work-days',
				'type' => 'text',
				'instructions' => 'Например: "ежедневно", "с пн. по пт."',
				'required' => 1,
				'default_value' => 'ежедневно',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5632d1468f781',
				'label' => 'Заголовок интерьеров',
				'name' => 'int-title',
				'type' => 'text',
				'instructions' => 'Заголовок раздела интерьеров',
				'default_value' => 'Интерьер ресторана',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 40,
			),
			array (
				'key' => 'field_563728f7d1433',
				'label' => 'Фоновое изображение заголовка интерьеров',
				'name' => 'int-background-image',
				'type' => 'text',
				'instructions' => 'Не редактировать',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5632c1d9aa27f',
				'label' => 'Описание интерьера',
				'name' => 'int-description',
				'type' => 'textarea',
				'instructions' => 'Краткое описание интерьера',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5632d1deae559',
				'label' => 'Заголовок меню',
				'name' => 'menu-title',
				'type' => 'text',
				'instructions' => 'Заголовок раздела меню',
				'default_value' => 'Меню ресторана',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 100,
			),
			array (
				'key' => 'field_5632c27faa280',
				'label' => 'Описание меню',
				'name' => 'menu-description',
				'type' => 'textarea',
				'instructions' => 'Краткое описание меню и кухни ресторана',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5632d0df34817',
				'label' => 'Описание проезда',
				'name' => 'where-text',
				'type' => 'text',
				'instructions' => 'О местоположении',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5632cc102faf1',
				'label' => 'Идентификатор',
				'name' => 'the-id',
				'type' => 'text',
				'instructions' => 'Не редактиуйте это',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_563315d2c58a1',
				'label' => 'Картинка в шапке',
				'name' => 'top-image',
				'type' => 'text',
				'instructions' => 'Не редактировать',
				'default_value' => 'rooms/1',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5637228db18a8',
				'label' => 'Фоновое видео в шапке',
				'name' => 'is-video',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5637230ca0450',
				'label' => 'Фотогалерея',
				'name' => 'rest-gallery',
				'type' => 'text',
				'instructions' => 'Не редактировать',
				'required' => 1,
				'default_value' => 'rooms/1 rooms/2 details/1 details/2',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-rest.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'author',
				4 => 'featured_image',
				5 => 'categories',
				6 => 'tags',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_%d1%80%d0%b5%d1%81%d1%82%d0%be%d1%80%d0%b0%d0%bd%d1%8b-%d0%bd%d0%b0-%d0%b3%d0%bb%d0%b0%d0%b2%d0%bd%d0%be%d0%b9',
		'title' => 'Рестораны на главной',
		'fields' => array (
			array (
				'key' => 'field_5636ecec99251',
				'label' => 'О ресторане',
				'name' => 'the-about',
				'type' => 'textarea',
				'instructions' => 'Описание ресторана, вкратце о ресторане',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5636ecec93482',
				'label' => 'Телефон',
				'name' => 'phone-number',
				'type' => 'text',
				'instructions' => 'Телефонный номер',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 10,
			),
			array (
				'key' => 'field_5636ecec9b180',
				'label' => 'Адрес',
				'name' => 'where',
				'type' => 'text',
				'instructions' => 'Адрес ресторана',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5636ecec924e7',
				'label' => 'Время работы',
				'name' => 'work-time',
				'type' => 'text',
				'instructions' => 'Время работы ресторана',
				'required' => 1,
				'default_value' => 'с 11:00 до 2:00',
				'placeholder' => 'с 11:00 до 2:00',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 25,
			),
			array (
				'key' => 'field_5636ecec94420',
				'label' => 'График работы',
				'name' => 'work-days',
				'type' => 'text',
				'instructions' => 'Например: "ежедневно", "с пн. по пт."',
				'required' => 1,
				'default_value' => 'ежедневно',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5636ed2d04264',
				'label' => 'SVG Лого',
				'name' => 'svg-logo',
				'type' => 'text',
				'instructions' => 'В папке шаблона ~/dest/images/svg',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5636ed6d1f269',
				'label' => 'Фоновое видео',
				'name' => 'background-video',
				'type' => 'text',
				'instructions' => 'В папке шаблона ~/dist/video',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5636eda51f26a',
				'label' => 'Фоновое изображение',
				'name' => 'background-image',
				'type' => 'text',
				'instructions' => 'В папке шаблона ~/dist/images/photos',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5636ede31f26b',
				'label' => 'Идентификатор',
				'name' => 'the-id',
				'type' => 'text',
				'instructions' => 'Не изменять',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'main_slider',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
*/
?>